export const REQUEST_DATA = 'REQUEST_DATA'
export const DATA_LOADED = 'DATA_LOADED'
export const LOADING_FAILS = 'LOADING_FAILS'
export const DATA_LOADED_AFTER_DELETE = 'DATA_LOADED_AFTER_DELETE'

export const ADDING_DATA = 'ADDING_DATA';
export const ADDING_DATA_FAILS = 'ADDING_DATA_FAILS';